# Generated by Django 5.1.7 on 2025-03-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='guess',
        ),
        migrations.RemoveField(
            model_name='player',
            name='room',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voted_player',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='player',
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='state',
        ),
        # Removed music-related fields
        # migrations.AddField(
        #     model_name='room',
        #     name='guest_can_pause',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='room',
        #     name='votes_to_skip',
        #     field=models.IntegerField(default=1),
        # ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
