# Generated by Django 5.1.7 on 2025-03-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_player_guess_remove_player_room_and_more'),
    ]

    operations = [
        # No operations needed as the fields were already commented out in the previous migration
    ]