# Generated by Django 5.1.7 on 2025-03-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_room_code'),
        ('api', '0003_remove_music_related_fields'),
    ]

    operations = [
    ]
