# Generated by Django 5.1.7 on 2025-03-24 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20250324_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truth_question', models.CharField(max_length=200)),
                ('liar_question', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='current_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='round_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='voting_phase',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('session_key', models.CharField(max_length=100)),
                ('is_host', models.BooleanField(default=False)),
                ('is_liar', models.BooleanField(default=False)),
                ('has_answered', models.BooleanField(default=False)),
                ('has_voted', models.BooleanField(default=False)),
                ('answer', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
                ('voted_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
                ('liar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
                ('question_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questionpair')),
            ],
        ),
    ]
