# Generated by Django 5.1.7 on 2025-03-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_room_current_game_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='session_key',
            field=models.CharField(max_length=50),
        ),
    ]
